### ISSUE TITLE
Does funny unicode things with IPv6 Adresses

### ISSUE THREAD

**Issue by crami** [The-Compiler/nasebohr#10]
Parts of IPv6 Addresses are replaced by a Unicode Character

![Screenshot from 2020-09-10 10-57-49](https://user-images.githubusercontent.com/206035/92706193-9b81d100-f354-11ea-8495-2c620ba57c9a.png)

**Comment by The-Compiler** [comment]
Thanks for the report! That's the emoji support in the [rich](https://rich.readthedocs.io/) library nasebohr uses for syntax highlighting:

```
>>> import rich
>>> rich.print(':otter: :abcd:')
🦦 🔡
```

I hope there's some way to turn that off (as we're only really interested in the colors)... I might switch to another color library as well, as `rich` does quite a bit of magic.

**Comment by willmcgugan** [comment]
You can disable emoji with `emoji=False` on the Console constructor, and highlighting with `highlight=False`.

The same arguments are on the `print()` function if you want to enable/disable them on a per print basis.

**Comment by The-Compiler** [comment]
@willmcgugan Amazing, thanks! I only looked at the [Console API docs](https://rich.readthedocs.io/en/latest/console.html) where this isn't mentioned, but after having another look found the [corresponding reference page](https://rich.readthedocs.io/en/latest/reference/console.html).

I think I will keep highlighting on, but will try to write a custom highlighter instead! Would be nice to highlight strings/numbers/IPs/... in the output, and rich *does* make that a lot easier compared to doing the same manually with a "simpler" library :slightly_smiling_face:

**Comment by willmcgugan** [comment]
A custom highlighter may be the way to go. I'm adding an ipv6 highlighter to the next version, if I can figure out the regex!
