### ISSUE TITLE
#!/usr/bin/env python3 Shebang?

### ISSUE THREAD

**Issue by papeng** [The-Compiler/nasebohr#12]
Hey Flo :)

Unless specified for a certain reason, I propose switching the shebang in `nasebohr.py` from `#!/usr/bin/python3` to `#!/usr/bin/env python3`, so the script can be used with e.g. the desired pyenv environment.

**Comment by The-Compiler** [comment]
Heya! :slightly_smiling_face: 

Seems reasonable! Want to open a PR?

**Comment by papeng** [comment]
Sure, there you go: https://github.com/The-Compiler/nasebohr/pull/13
