### ISSUE TITLE
rich highlighting fails with IPs

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/nasebohr#4]
![image](https://user-images.githubusercontent.com/625793/92414837-49735c80-f156-11ea-8d77-05962ff0be36.png)

The white dot doesn't belong there.

**Comment by jsav0** [comment]
I don't appear to have this issue. Can not duplicate. Was it resolved?
![image](https://user-images.githubusercontent.com/20546041/93670072-61a47f00-fa66-11ea-803a-182ca58093d5.png)

**Comment by The-Compiler** [comment]
@jsav0 Looks like this was recently fixed in rich, as it now highlights IPv4/IPv6 addresses properly by default: https://github.com/willmcgugan/rich/commit/2341b224586548a258e4905b73a22f68d0a2ee0b

Thanks @willmcgugan!
